### ISSUE TITLE
らじるらじるが聴取できない

### ISSUE THREAD

**Issue by melton2145** [t-yoshi/RadiRuKo-Plugin#1]
2015年9月から12月の間に、NHKのらじるらじる配信サーバーのリニューアルが行なわれたため
らじるらじるが完全に聴取できなくなりました。
個人的に調査してみたのですが、プラグインに同梱されている ffmpeg が
RTMPE プロトコル type 8 に完全対応していないことが原因と思われます。

最新の ffmpeg では対応されている様（少なくともソースコード上はそう見える）ですので
おそらくは ffmpeg のアップデートのみで問題は解消するかと思います。
すみませんが、ご対応よろしくお願いいたします。

**Comment by melton2145** [comment]
プラグインに同梱されている ffmpeg-1.1 を 2.8.4 へ入れ替えたところ
問題なく聴取できました(QNAP TS-269 Pro)。
Radiko と JCBA についても問題ありません。
まずはご一報まで。

**Comment by t-yoshi** [comment]
情報に感謝です。
やるべきことも多いのですが、更新をお待ち下さい。

**Comment by melton2145** [comment]
回答ありがとうございます。
申し遅れましたが、大変便利に使わせていただいてます。
更新のほう、気長にお待ちしていますのでよろしくお願いいたします。
