### ISSUE TITLE
Ver 8.0 がダウンロードできない

### ISSUE THREAD

**Issue by rideryancha** [t-yoshi/RadiRuKo-Plugin#10]
プラグインのダウンロードに失敗します。
ログを見ていると404 errorなので、ダウンロード先のURLが"http:"ではなく"https:"が正しい気がします。

unable to download RadiRuKo from http://t-yoshi.github.io/RadiRuKo-Plugin/release/v8/dest/RadiRuKo-8.0.0.zip - 404 Not Found

**Comment by t-yoshi** [comment]
修正済み
