### ISSUE TITLE
コミュニティFMにFMおたるを追加して頂けないでしょうか

### ISSUE THREAD

**Issue by fencewalker** [t-yoshi/RadiRuKo-Plugin#2]
プラグインを公開して下さり、ありがとうございます。

 FMおたる　http://fmotaru.jp/
CSRA内ページ　http://csra.fm/blog/author/fmotaru/
再生用URL　http://csra.fm/asx/otaru.asx

お手隙の際にでも、追加して頂ければ幸いです。

**Comment by t-yoshi** [comment]
追加しておきました。キャッシュを設定してるので、更新まで数日お待ちください。

コミュニティFMリストの更新は、数カ月に一度気の向いた時にやってます。
あたらしい放送局については、各自お気に入りの登録等で対処願います。

**Comment by fencewalker** [comment]
追加して頂き、ありがとうございます。

＞あたらしい放送局については、各自お気に入りの登録等で対処願います。
この機能の事を失念しておりました…、お手数をお掛けして誠に申し訳ありません。
