### ISSUE TITLE
【要望】 Rakuten.FM への対応

### ISSUE THREAD

**Issue by melton2145** [t-yoshi/RadiRuKo-Plugin#3]
いつも便利に利用させていただいています。
7月1日より Rakuten.FM (http://rakuten.fm) がサービス開始しました。
こちら、機能実装のご検討をいただけると助かります。

**Comment by t-yoshi** [comment]
あれは技術的に難しいと思います。
最近はrazikoの件があるので目立つことはしないほうがいいでしょう。

**Comment by melton2145** [comment]
今ざっと確認していますが、これ Icecast 鯖が丸見えですね…。
いずれ塞がれそうですが、今のところストリームキャプチャするだけならそれほど難しくはないと思います。
ただ、ご指摘の通り今 Raziko の件が結構面倒臭いことになってるので、静観するという選択も納得できます。
回答ありがとうございました。

**Comment by melton2145** [comment]
Rakuten.FM へのご対応ありがとうございました。
Squeezeboxディスコンからはや数年経過していますが
現在でも新規機能を追加してリリースされている事は、決して少なくない日本人利用者にとって
大変心強く感じると思います（もちろん私も含めて）。

ただ、実装が大きく変わったことによって
機能追加部分だけでなく従来機能についても挙動が不安定になっているようです。
自分の環境が LMS 7.9 の所為かもしれませんが
後ほど改めて詳細ご報告させていただきます。

**Comment by melton2145** [comment]
Rakuten.FM が2017年8月いっぱいでサービスクローズしたようです。
1年という短い間でしたが、プラグインのご提供ありがとうございました。
