### ISSUE TITLE
【らじるこ基本 v5.0-16/09/15】選局に失敗する⇒LMS操作不能になる

### ISSUE THREAD

**Issue by melton2145** [t-yoshi/RadiRuKo-Plugin#5]
o 内容
-- らじるこプラグインメニュー配下に表示されている局の選局を数回繰り返すと、操作不能になる。
-- 一度操作不能になると、LMS上の他の操作についても全く受け付けなくなる(LMSがクラッシュする)。
-- Webインターフェイス・SQB端末どちらからも操作を受け付けなくなる。
-- LMSを再起動すると正常に動き出すが、その後選局を何回か繰り返すと同様の現象が発生する。
-- 現象発生時、server.log に以下の出力があった。

```
[16-09-27 14:19:05.8071] Slim::Networking::IO::Select::__ANON__ (131) Error: Select task failed calling Slim::Networking::Async::HTTP::_http_read_body: panic: attempt to copy freed scalar d9df8a8 to d5d21d8 at /opt/ssods4/var/home/SqueezeboxServer/Cache/InstalledPlugins/Plugins/RadiRuKo/Utils.pm line 51.
; fh=Slim::Networking::Async::Socket::HTTP=GLOB(0xd5d3188)
```

o 再現手順
-- 手順による再現性は見出せない。

o 実行環境
-- Server
--- Qnap TS-269 Pro (CPU:IntelAtom/Memory:3GB)
--- LMS 7.9.0 - 1474277583 @ Sun Sep 25 04:07:24 UTC 2016 (SSOTS 4.14)
-- Player
--- Squeezebox Radio (FW:7.7.3-r16676)

**Comment by t-yoshi** [comment]
いずれの問題も当方ではまったく起きていないので、
原因は私にはわかりません。

以下の環境で完全に動作することを確認しています。

　開発は継続しているので、問題が解決するかは知りませんが
そのうちアップデートはします。

| OS | LMS | Perl |
| --- | :-: | --- |
| Scientific5/i686 | 7.6.2 | 5.8.8 |
| Debian8/amd64 | 7.9.0 | 5.20.2 |
| FreeBSD10/amd64 | 7.5.4 | 5.16.3 |
| WindowsXP | 7.8.0 | ----- |
| Buffalo LS-XHL | 7.9.0 | 5.14.2 |

SqueezePlay 7.8.0-r328
SqueezeBox Touch 7.8.0-r16754

**Comment by melton2145** [comment]
お返事遅くなりまして申し訳ありません。ご確認ありがとうございます。
おそらくですが SSOTS に同梱されていないモジュールを呼び出されているのではないかと思われます。
そのため QNAP ユーザーには同様の問題が発生しているような気がします。

ひとまず前のバージョンに戻して利用させていただいてます。
もしよろしければ、ご対応のほどよろしくお願いいたします。

**Comment by melton2145** [comment]
現在も server.log 上に時折エラーログが出力されてますが
LMS がフリーズすることは無くなり、表面上は問題なく動作しているようです。
遅くなりましたが対応ありがとうございました。
本件クローズさせていただきます。
