### ISSUE TITLE
エリアが大阪固定になってしまいます

### ISSUE THREAD

**Issue by ueki-hikonuki** [t-yoshi/RadiRuKo-Plugin#9]
東京エリアですが常に大阪と判定されてしまいます。

FAQで「 エリア判定のため、LMS起動直後はネットに接続されている必要がある。」とありますが、常にネットには接続されています。

キャッシュを削除しても同じでした。

バージョンは7.0.1です。

**Comment by t-yoshi** [comment]
貴方の回線、プロバイダの問題。

>「 エリア判定のため、LMS起動直後はネットに接続されている必要がある。」

現バージョンでは関係ないので消します。

**Comment by ueki-hikonuki** [comment]
radikoのFAQの「今いるエリアの放送局を聴取できない （他のエリアの放送局が表示される）」のところから、エリア判定の修正依頼申告をすると二日程度で直りした。
